substitutions:
  name: esphome-web-xxxxxx
  friendly_name: Hifi-Esparagus
  task_stack_in_psram: "false" # important to disable this for non-S3 model

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.7.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: mhetesp32minikit
  flash_size: 8MB
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  
wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  ap:
    ssid: "$name Hotspot"
    password: !secret esphome_ap_password

captive_portal:

# Allow Over-The-Air updates
ota:
  platform: esphome
  password: !secret esphome_ota_password

# Enable Home Assistant API
api:

psram:
  speed: 80MHz

globals:
  - id: current_volume
    type: float

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26

media_player:
  - platform: i2s_audio
    name: HiFi Mediaplayer
    id: hifi_mediaplayer
    dac_type: external
    i2s_dout_pin: GPIO22

    on_announcement:
      - light.turn_on:
          id: rgb_front_led
          blue: 100%
          red: 0%
          green: 100%
          brightness: 50%

      - wait_until:
          not:
            media_player.is_announcing:

      - light.turn_off:
          id: rgb_front_led

### RGB light config
light:
  - platform: esp32_rmt_led_strip
    id: rgb_front_led
    name: "${friendly_name} LED"
    rgb_order: GRB
    pin: GPIO33
    num_leds: 1
    chipset: ws2812
    default_transition_length: 0s

### IR reader config. Add your own IR codes as needed
remote_receiver:
  pin: 
    number: GPIO39
    inverted: true
    mode:
      input: true
  dump: all

button:
  - platform: restart
    id: restart_btn
    name: "${friendly_name} REBOOT"
