# ============================================================
# PCM5122 DAC - I2C Control, Digital volume, Gain and Mute
# ============================================================
# Requires substitutions:
#   - i2c_sda_pin
#   - i2c_scl_pin
# ============================================================

substitutions:
  pcm5122_dac_restore_mode: ALWAYS_OFF
  pcm5122_dac_analog_gain: 0dB
  pcm5122_i2c_address: 0x4d
  pcm5122_max_volume_db: 0dB
  pcm5122_min_volume_db: -60dB
  pcm5122_dac_mixer_mode: stereo

i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  frequency: 400kHz
  scan: true

audio_dac:
  - platform: pcm5122
    id: external_dac
    address: ${pcm5122_i2c_address}          # I2C address of the DAC, it is 0x4C n the HiFi-ESP32 Rev H, and 0x4D on the rev H1+
    volume_max_db: ${pcm5122_max_volume_db}  # maximum volume range 0dB, can go up to +24dB
    volume_min_db: ${pcm5122_min_volume_db}  # minimum volume range -60dB, can go down to -103dB
    analog_gain: ${pcm5122_dac_analog_gain}  # or -6Db for 1V RMS output, default is 0dB = 2V RMS output
    channel_mix: ${pcm5122_dac_mixer_mode}   # mixermode: stereo, swapped, left, right

switch:
  - platform: pcm5122
    pcm5122: external_dac
    name: "PCM5122 Power On"
    id: enable_dac
    restore_mode: ${pcm5122_dac_restore_mode}
    inverted: true