# ============================================================
# Rotary Encoder - Button and Encoder Sensor
# ============================================================
# Requires substitutions:
#   - friendly_name
#   - rotary_pin_a
#   - rotary_pin_b
#   - rotary_btn_pin
# ============================================================

binary_sensor:
  - platform: gpio
    id: rotary_btn
    name: "${friendly_name} Rotary button"
    pin: 
      number: ${rotary_btn_pin}
      mode:
        input: true
        pullup: true
      inverted: true

sensor:
  - platform: rotary_encoder
    id: rotary_dial
    name: "${friendly_name} Rotary Encoder"
    pin_a: ${rotary_pin_a}
    pin_b: ${rotary_pin_b}

