# ============================================================
# Sendspin - Amp unmute addon
# ============================================================
# Configures sendspin component to switch on and off amp on playback events
# Requires substitutions:
#   - task_stack_in_psram
#   - amp_enable_pin
# ============================================================

media_player:
  - id: !extend external_media_player

    on_play:
      - if:
          condition:
            switch.is_off: enable_amp
          then:
            switch.turn_on: enable_amp

    on_idle:
      - if:
          condition:
            switch.is_on: enable_amp
          then:
            switch.turn_off: enable_amp
