# ============================================================
# TFT display - Shows simple clock using the ILI9341 240x320 TFT connected via SPI
# ============================================================
# Requires substitutions:
#   - spi_clk_pin
#   - spi_mosi_pin
#   - spi_miso_pin
#   - display_cs_pin
#   - display_dc_pin
#   - display_reset_pin
# ============================================================

# prerequisites:
font:
  - file:
      type: gfonts
      family: Roboto
      weight: regular
    id: roboto_medium
    size: 32
    glyphs: [' ', ':', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

spi:
  clk_pin: ${spi_clk_pin}
  mosi_pin: ${spi_mosi_pin}
  miso_pin: ${spi_miso_pin}

time:
  - platform: sntp
    id: sntp_time

switch:
  - platform: gpio
    name: "Display Backlight"
    id: display_backlight
    pin:
      number: ${display_backlight_pin}
    restore_mode: ALWAYS_ON

### Example display configuration, showing the current playback state
display:
  - platform: ili9xxx
    id: tft_display
    model: ILI9341
    dimensions:
      width: 320
      height: 240
      offset_height: 0
      offset_width: 0
    invert_colors: true
    dc_pin: ${display_dc_pin}
    reset_pin: ${display_reset_pin}
    cs_pin: ${display_cs_pin}
    rotation: 90
    update_interval: 5s
    lambda: |-
      it.fill(id(Color::BLACK));
        // display clock
        auto hours = id(sntp_time).now().hour;
        auto minutes = id(sntp_time).now().minute;
        auto seconds = id(sntp_time).now().second;
        auto dot = seconds % 2 == 0 ? " " : ":";
        it.printf(64, 32, id(roboto_medium), TextAlign::CENTER, "%d%s%02d", hours, dot ,minutes);